{% set name = "gtsam" %}
{% set version = "4.3a1" %}

package:
  name: gtsam
  version: '{{ version }}'

source:
  url: https://github.com/borglab/gtsam/archive/refs/tags/{{ version }}.tar.gz
  sha256: 4233192fd9154aa2c0ccd05aebd833d8bf67307888774895e7b3b3d98b31607a
  patches:
    - nobuild-examples-timing.patch
    - fix-python-build-win.patch  # [win]
    - fix-boost.patch  # [win]
    - fix-missing-includes.patch
    - fix-linux-link-libm-for-cephes.patch  # [unix]
    - windows_python_fix_part_of_pr1685.patch

build:
  number: 2
  run_exports:
    - '{{ pin_subpackage(name, max_pin="x.x") }}'

requirements:
  build:
    - '{{ compiler("c") }}'
    - {{ stdlib("c") }}
    - '{{ compiler("cxx") }}'
    - ninja
    - cmake
    - pybind11                               # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - libboost-devel
    - eigen
    - geographiclib-cpp
    - metis
    - suitesparse
    - tbb
    - tbb-devel
    - pybind11
    - pyparsing
    - numpy
    - setuptools
    - pip
  run:
    - python
    - pyparsing
    - numpy

test:
  commands:
    - |
      if [ "${CONDA_BUILD_CROSS_COMPILATION:-0}" != "1" ]; then
        python - <<'PY'
        import gtsam
        import numpy as np

        graph = gtsam.NonlinearFactorGraph()
        x0, v0, b0 = gtsam.symbol("x", 0), gtsam.symbol("v", 0), gtsam.symbol("b", 0)
        pose0 = gtsam.Pose3(np.eye(4))
        vel0 = np.zeros(3)
        bias0 = gtsam.imuBias.ConstantBias()

        graph.add(gtsam.PriorFactorPose3(x0, pose0, gtsam.noiseModel.Isotropic.Sigma(6, 0.1)))
        graph.add(gtsam.PriorFactorVector(v0, vel0, gtsam.noiseModel.Isotropic.Sigma(3, 0.1)))
        graph.add(gtsam.PriorFactorConstantBias(b0, bias0, gtsam.noiseModel.Isotropic.Sigma(6, 0.1)))

        values = gtsam.Values()
        values.insert(x0, pose0)
        values.insert(v0, vel0)
        values.insert(b0, bias0)

        x1, v1, b1 = gtsam.symbol("x", 1), gtsam.symbol("v", 1), gtsam.symbol("b", 1)
        pose1 = gtsam.Pose3(np.eye(4))
        graph.add(gtsam.PriorFactorPose3(x1, pose1, gtsam.noiseModel.Diagonal.Sigmas(np.full(6, 0.1))))

        imu = gtsam.PreintegratedImuMeasurements(gtsam.PreintegrationParams(np.array([0.0, 0.0, 9.81])))
        pred = imu.predict(gtsam.NavState(pose0, vel0), bias0)
        graph.add(gtsam.ImuFactor(x0, v0, x1, v1, b1, imu))
        graph.add(
            gtsam.BetweenFactorConstantBias(
                b0, b1, gtsam.imuBias.ConstantBias(), gtsam.noiseModel.Diagonal.Sigmas(np.full(6, 0.1))
            )
        )

        values.insert(x1, pred.pose())
        values.insert(v1, pred.velocity())
        values.insert(b1, gtsam.imuBias.ConstantBias())

        gtsam.ISAM2(gtsam.ISAM2Params()).update(graph, values)
        PY
      fi
      # [not win]
    - test -f ${PREFIX}/lib/libgtsam${SHLIB_EXT}  # [not win]
    - test -f ${PREFIX}/lib/cmake/gtwrap/gtwrapConfig.cmake  # [not win]
    - test -f ${PREFIX}/lib/cmake/GTSAM/GTSAMConfig.cmake  # [not win]
    - test -f ${PREFIX}/include/gtsam/base/types.h  # [not win]
    - if exist %PREFIX%\\Library\\include\\gtsam\\base\\types.h (exit 0) else (exit 1)  # [win]
    - if exist $PREFIX$\\Library\\lib\\gtsam.lib (exit 0) else (exit 1)  # [win]
    - if exist $PREFIX$\\Library\\bin\\gtsam.dll (exit 0) else (exit 1)  # [win]
  imports:
    - gtsam


about:
  home: https://github.com/borglab/gtsam
  summary: GTSAM is a library of C++ classes that implement smoothing and mapping (SAM) in robotics and vision
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - LICENSE.BSD

extra:
  recipe-maintainers:
    - wolfv
    - ameysutavani
    - Tobias-Fischer
    - traversaro
